//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTREP_Cafeteria_Food_Tracker_MANAGEMENT_SYSTEM
{


    public partial class Analytics
    {
        protected global::System.Web.UI.WebControls.Literal DateRangeText;
        protected global::System.Web.UI.WebControls.TextBox StartDateInput;
        protected global::System.Web.UI.WebControls.TextBox EndDateInput;
        protected global::System.Web.UI.WebControls.Button ApplyDateRangeButton;
        protected global::System.Web.UI.WebControls.Label DateRangeError;
        protected global::System.Web.UI.WebControls.Literal TotalRevenueValue;
        protected global::System.Web.UI.WebControls.Literal WeeklyTransactionCount;
        protected global::System.Web.UI.WebControls.Literal ItemsSoldValue;
        protected global::System.Web.UI.WebControls.Literal BestSellerName;
        protected global::System.Web.UI.WebControls.Literal BestSellerUnits;
        protected global::System.Web.UI.WebControls.Repeater DailySalesRepeater;
        protected global::System.Web.UI.WebControls.Repeater TopProductsRepeater;
        protected global::System.Web.UI.WebControls.Literal BestSalesDayText;
        protected global::System.Web.UI.WebControls.Literal TopPerformerText;
        protected global::System.Web.UI.WebControls.Literal TodayActivityText;
    }
}
