//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTREP_Cafeteria_Food_Tracker_MANAGEMENT_SYSTEM
{
    public partial class Products
    {
        protected global::System.Web.UI.WebControls.Button BtnOpenAddProduct;
        protected global::System.Web.UI.WebControls.Panel AlertPanel;
        protected global::System.Web.UI.WebControls.Literal AlertMessage;
        protected global::System.Web.UI.WebControls.LinkButton btnDismissAlert;

        protected global::System.Web.UI.WebControls.Literal TotalProductsValue;
        protected global::System.Web.UI.WebControls.Literal CategoryCountValue;
        protected global::System.Web.UI.WebControls.Literal ActiveProductsValue;
        protected global::System.Web.UI.WebControls.Literal LowStockProductsValue;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategoryFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlStockFilter;
        protected global::System.Web.UI.WebControls.Literal ProductCountText;

        protected global::System.Web.UI.WebControls.Repeater ProductRepeater;
        protected global::System.Web.UI.WebControls.Panel EmptyProductsPanel;

        protected global::System.Web.UI.WebControls.Panel ProductModal;
        protected global::System.Web.UI.WebControls.Literal ModalTitle;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseModal;
        protected global::System.Web.UI.WebControls.HiddenField hfProductID;
        protected global::System.Web.UI.WebControls.ValidationSummary ModalValidationSummary;
        protected global::System.Web.UI.WebControls.Label ModalErrorMessage;

        protected global::System.Web.UI.WebControls.TextBox txtProductName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvProductName;

        protected global::System.Web.UI.WebControls.DropDownList ddlModalCategory;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvModalCategory;

        protected global::System.Web.UI.WebControls.TextBox txtUnitPrice;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUnitPrice;
        protected global::System.Web.UI.WebControls.RangeValidator rvUnitPrice;

        protected global::System.Web.UI.WebControls.TextBox txtCostPrice;
        protected global::System.Web.UI.WebControls.RangeValidator rvCostPrice;

        protected global::System.Web.UI.WebControls.TextBox txtStockQty;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvStockQty;

        protected global::System.Web.UI.WebControls.TextBox txtReorderLevel;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvReorderLevel;

        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        protected global::System.Web.UI.WebControls.Button btnCancelProduct;
        protected global::System.Web.UI.WebControls.Button btnSaveProduct;
    }
}
