//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTREP_Cafeteria_Food_Tracker_MANAGEMENT_SYSTEM
{
    public partial class Sales
    {
        protected global::System.Web.UI.WebControls.Button BtnOpenRecordSale;
        protected global::System.Web.UI.WebControls.Panel SaleAlertPanel;
        protected global::System.Web.UI.WebControls.Literal SaleAlertMessage;
        protected global::System.Web.UI.WebControls.LinkButton btnDismissSaleAlert;

        protected global::System.Web.UI.WebControls.Literal SalesTotalValue;
        protected global::System.Web.UI.WebControls.Literal TodayDateText;
        protected global::System.Web.UI.WebControls.Literal TodayTransactionCount;
        protected global::System.Web.UI.WebControls.Literal AverageSaleValue;
        protected global::System.Web.UI.WebControls.Literal SalesRowsText;

        protected global::System.Web.UI.WebControls.TextBox txtSaleSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlSessionFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlPaymentFilter;

        protected global::System.Web.UI.WebControls.Repeater SalesRepeater;
        protected global::System.Web.UI.WebControls.Panel EmptySalesPanel;

        protected global::System.Web.UI.WebControls.Panel SaleModal;
        protected global::System.Web.UI.WebControls.LinkButton btnCloseSaleModal;
        protected global::System.Web.UI.WebControls.ValidationSummary SaleValidationSummary;
        protected global::System.Web.UI.WebControls.Label SaleErrorMessage;

        protected global::System.Web.UI.WebControls.DropDownList ddlSaleProduct;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSaleProduct;

        protected global::System.Web.UI.WebControls.TextBox txtSaleQuantity;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSaleQuantity;
        protected global::System.Web.UI.WebControls.RangeValidator rvSaleQuantity;

        protected global::System.Web.UI.WebControls.DropDownList ddlSaleSession;
        protected global::System.Web.UI.WebControls.DropDownList ddlSalePaymentMethod;

        protected global::System.Web.UI.WebControls.TextBox txtSaleDiscount;
        protected global::System.Web.UI.WebControls.RangeValidator rvSaleDiscount;

        protected global::System.Web.UI.WebControls.TextBox txtSaleCashier;
        protected global::System.Web.UI.WebControls.TextBox txtSaleNotes;

        protected global::System.Web.UI.WebControls.Button btnCancelSale;
        protected global::System.Web.UI.WebControls.Button btnSubmitSale;
    }
}
