//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTREP_Cafeteria_Food_Tracker_MANAGEMENT_SYSTEM
{


    public partial class Sales
    {

        protected global::System.Web.UI.WebControls.Repeater SalesRepeater;

        protected global::System.Web.UI.WebControls.Literal SalesTotalValue;
        protected global::System.Web.UI.WebControls.Literal TodayTransactionCount;
        protected global::System.Web.UI.WebControls.Literal AverageSaleValue;
        protected global::System.Web.UI.WebControls.Literal TodayDateText;
        protected global::System.Web.UI.WebControls.Literal SalesRowsText;
    }
}
