//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTREP_Cafeteria_Food_Tracker_MANAGEMENT_SYSTEM
{


    public partial class SiteMaster
    {

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AccountToolbar;
        protected global::System.Web.UI.WebControls.Literal AuthenticatedUserName;
        protected global::System.Web.UI.WebControls.LinkButton LogoutButton;
        protected global::System.Web.UI.WebControls.Panel TrackerSidebar;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor OverviewLink;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor ProductsLink;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor SalesLink;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor AnalyticsLink;
        protected global::System.Web.UI.WebControls.Literal UserInitials;
        protected global::System.Web.UI.WebControls.Literal SidebarUserName;

        /// <summary>
        /// MainContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
